# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JoUbPhudHLZdVJhGsi4Zw33NqwmFF8Wv
"""

import streamlit as st

st.title("私の初めての Streamlit アプリ")
st.write("こんにちは、Streamlit！")

# スライダーを追加
x = st.slider("x の値を選んでください", 0, 100, 25)
st.write("x の値は", x, "です")

# ボタンを追加
if st.button("クリックしてください"):
    st.write("ボタンがクリックされました！")